stages:
  - deploy
image: node:latest
pages:
  stage: deploy
  script:
    - npm rebuild node-sass
    - npm i
    - npm run build
    - rm -rf public
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - master
