stages:
  - deploy
image: node:latest
pages:
  stage: deploy
  script:
    - npm i
    - npm run build
    - mkdir -p page
    - mv dist/* page
  artifacts:
    paths:
      - page
  only:
    - master
