stages:
  - deploy
image: node:latest
before_script:
  - npm ci
pages:
  stage: deploy
  script:
    - npm run build
    - cp -r ./dist/* ./public
  artifacts:
    paths:
      - public
  only:
    - master
